apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: worker
    template:
        metadata:
            labels:
                component: worker
        spec:
            containers:
                - name: worker
                  image: stephengrider/multi-worker
                  #ports:
                    #- containerPort: 1234 # No need for port because no other app will connect to it either from outside or inside.
                  env:
                    - name: REDIS_HOST
                      value: redis-cluster-ip-service
                    - name: REDIS_PORT
                      value: '6379'

# We also don't need service config for worker because, we don't want anything to connect to worker
# either from outside or from inside. Worker will only connect to redis.